name: Kevin P. Russell
favicon: null
layout_spectrum: 0.24391
typography_spectrum: 0.75238
title: Kevin P. Russell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b263c'
    - '#d6d5d3'
    - '#c22227'
    - '#b38773'
    - '#6abd69'
  brandStrength: 0.07954648812301457
  lightness: 0.5390344180632383
  saturation: 0.1875
  rhythmicContrast: 0.4238892968278378
purpose: []
